Уровень 0:  
Задание 1  
- Создайте матрицу 3 на 3, заполненную числами от 1 до 9
-Прибавьте к ней матрицу с единицами на диагонале
-Умножьте полученную матрицу на вектор (1, 2, 3)
-Вычислить транспонированную матрицу
от полученной в результате прибавления матрицы
-Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
import numpy as np

"""Создание матрицы 3 на 3, заполненную числами от 1 до 9"""

a1 = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
"""Прибавляем к ней матрицу с единицами на диагонале"""

a2 = np.eye (3)
print(a2)
a3 = a1 + a2
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [ ]:
"""Умножаем полученную матрицу на вектор (1, 2, 3)"""

vec = [1,2,3]
a4 = a3 @ vec
print(a4)

[15. 34. 53.]


In [ ]:
"""Вычисляем транспонированную матрицу от полученной в результате прибавления матрицы"""

a_tran = a3.transpose()
print(a_tran)

[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]


In [ ]:
"""Посчитайте обратную матрицу к полученной в результате прибавления матрице"""

a_rever = np.linalg.inv (a3)
a_rever = np.round(a_rever)
print(a_rever)

[[-6. -2.  3.]
 [-1.  1. -0.]
 [ 5.  1. -2.]]


In [ ]:
"""Уровень 1:
Задание 2
Найдите собственные значения и собственные вектора матрицы:"""

m = np.array([[2, 2],
              [1, 3]])
print(m)
m_eig = np.linalg.eig (m)
print(m_eig)

[[2 2]
 [1 3]]
EigResult(eigenvalues=array([1., 4.]), eigenvectors=array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]]))


In [ ]:
"""Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!"""

mat = np.array([[1, 1, 4], [1, 1, 3], [1, 2, 1]])
"""Вычисляем определитель"""
det_mat = np.linalg.det(mat)
print(mat)
print(det_mat)

[[1 1 4]
 [1 1 3]
 [1 2 1]]
1.0
